Fix syntax error

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -39,14 +39,7 @@ jobs:
 
         # Check whether image is present
         jq '.image' userinfo.json > userimage 
-        if grep -q "null" ./userimage ; then
-          if [ -f "./images/$userImage"]; then
-            echo "image verified!"
-          else
-            echo "image file not found"
-            exit 1
-          fi
-        fi
+        if grep -q "null" ./userimage;then if [ -f "./images/$userImage"];then;echo "image verified!";else;echo "image file not found";exit 1;fi;fi;
 
       - name: Cleanup
         run: |
